steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'edusiap-app'  # Ini wajib! agar Dockerfile di dalam edusiap-app dikenali
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/edusiap', '.']

images:
  - 'gcr.io/$PROJECT_ID/edusiap'
