steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci
        NEXT_DISABLE_LINT=true NEXT_IGNORE_TYPE_ERRORS=true npm run build
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
